# Uncomment the next line to define a global platform for your project
 # platform :ios, '9.0'

target 'Barber' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Barber
pod 'Stripe', '~> 14.0.0'
pod 'Firebase/Core', '~> 5.19.0'
pod 'Firebase/Messaging', '~> 5.19.0'
pod 'Firebase/DynamicLinks', '~> 5.19.0'
  target 'Barber-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    #pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  end

  target 'BarberTests' do
    inherit! :search_paths
    # Pods for testing
  end

end 

post_install do |installer|
  system("mkdir -p Pods/Headers/Public/FirebaseCore && cp Pods/FirebaseCore/Firebase/Core/Public/* Pods/Headers/Public/FirebaseCore/")
end
